stages:
  - test

test:
  stage: test
  needs: []
  services:
    - name: $CI_REGISTRY/tke/knowledge-engine/smart-connector-rest-dist:1.1.1
      alias: tke-runtime
  image:
    name: python:3.10
    entrypoint: [""]
  variables:
    KE_RUNTIME_URL: http://tke-runtime:8280/rest
  script:
    - pip install -r ./dev-requirements.txt
    - pytest
