stages:
  - test

test:
  stage: test
  needs: []
  services:
    - name: ghcr.io/tno/knowledge-engine/smart-connector:1.1.3
      alias: tke-runtime
  image:
    name: python:3.10
    entrypoint: [""]
  variables:
    KE_RUNTIME_URL: http://tke-runtime:8280/rest
  script:
    - cd ./mapper
    - pip install -r ./dev-requirements.txt
    - pytest
