services:
  sc:
    image: ci.tno.nl/tke/knowledge-engine/smart-connector-rest-dist:0.1.11
    ports:
      - 8280:8280
  fuseki:
    image: stain/jena-fuseki
    ports:
      - 3030:3030
    volumes:
      - ./test/config.ttl:/fuseki/config.ttl
      - ./test/data.ttl:/fuseki/data.ttl
  fuseki-auth:
    image: stain/jena-fuseki
    ports:
      - 3031:3030
    volumes:
      - ./test/config.ttl:/fuseki/config.ttl
      - ./test/data.ttl:/fuseki/data.ttl
      - ./test/shiro.ini:/fuseki/shiro.ini
