services:
  knowledge-engine:
    image: ghcr.io/tno/knowledge-engine/smart-connector:1.1.3
    ports:
      - "8280:8280"
  knowledge-mapper:
    build: ./mapper
    entrypoint: [ "python", "-m", "knowledge_mapper", "ignored", "--wizard" ]
    environment:
      - KM_API=http://km-api:8000/km
    depends_on:
      - km-api
  km-api:
    build: ./api
    env_file:
      - km-api.env
    environment:
      KE_ENDPOINT: http://knowledge-engine:8280/rest
    # TODO: Persist data in volume
    depends_on:
      - knowledge-engine
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - km-api
