[project]
name = "knowledge-mapper"
version = "0.1.0rc1"
description = "The Knowledge Mapper makes it easier to share your data in a knowledge base to the TNO Knowledge Engine (TKE) network."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28",
    "pydantic>=2.12.5",
    "pydantic-settings[yaml]>=2.13.1",
    "rdflib>=7.6.0",
    "typer>=0.15",
]

[project.scripts]
knowledge-mapper = "knowledge_mapper.cli:app"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=0.26",
    "setuptools>=82.0.1",
]

# TOOLS - pytest

[tool.pytest.ini_options]
minversion = "6.0"
asyncio_mode = "auto"
addopts = [
    "--import-mode=importlib",
    "-ra",
    "-q",
]
filterwarnings = [
    "ignore:cannot collect test class 'TestClient':pytest.PytestCollectionWarning",
]


# TOOLS - ruff

[tool.ruff]
exclude = [
    ".pytest_cache",
    ".venv",
]
line-length = 88
indent-width = 4
target-version = "py313"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]

[tool.ruff.format]
quote-style = "double"

[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
