# Generated by Django 4.1.3 on 2022-11-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_url", models.CharField(max_length=512, unique=True)),
                ("name", models.CharField(max_length=512)),
                ("description", models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_url", models.CharField(max_length=512, unique=True)),
                ("name", models.CharField(max_length=512)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ASK", "AskKnowledgeInteraction"),
                            ("ANSWER", "AnswerKnowledgeInteraction"),
                            ("POST", "PostKnowledgeInteraction"),
                            ("REACT", "ReactKnowledgeInteraction"),
                        ],
                        max_length=6,
                    ),
                ),
                ("prefixes", models.JSONField(blank=True)),
                ("pattern_1", models.TextField()),
                ("pattern_2", models.TextField(blank=True, null=True)),
                (
                    "kb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="km.knowledgebase",
                    ),
                ),
            ],
        ),
    ]
