# Generated by Django 4.1.2 on 2022-10-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kb_id", models.CharField(max_length=512)),
                ("name", models.CharField(max_length=512)),
                ("description", models.CharField(max_length=512)),
            ],
        ),
    ]
