# Generated by Django 4.1.3 on 2022-11-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("km", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebase",
            name="kb_id",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
