services:
  # This service is the TNO Knowledge Engine runtime where all interoperability is interoperated.
  tke-runtime:
    image: ci.tno.nl/tke/knowledge-engine/smart-connector-rest-dist:1.1.3
    ports:
      - 8280:8280
  
  # Data source 1: A triple store with a SPARQL endpoint.
  triple-store:
    image: oxigraph/oxigraph
    platform: linux/amd64
    ports:
      - 7878:7878
    volumes:
      - ./triple-store/data.ttl:/seed-data/data.ttl
      - ./triple-store/start.sh:/start.sh
    entrypoint: /start.sh

  # Knowledge mapper for the SPARQL endpoint
  sparql-mapper:
    build:
      context: ..
      dockerfile: ./examples/sparql-mapper/Dockerfile
    environment:
      SPARQL_USERNAME: user
      SPARQL_PASSWORD: password
  
  # Data source 2: An SQL database
  sql-db:
    image: mariadb:10.5
    ports:
      - 3306:3306
    volumes:
      - ./sql-db/seed_data:/docker-entrypoint-initdb.d/:ro
    environment:
      MARIADB_DATABASE: treedb
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_RANDOM_ROOT_PASSWORD: 1

  # Knowledge mapper for the SQL database
  sql-mapper:
    build:
      context: ..
      dockerfile: ./examples/sql-mapper/Dockerfile

  # This is a custom knowledge mapper without an underlying data source that
  # uses a Python function to generate its data. You can imagine that it is
  # possible to disclose sources like REST APIs this way, but it requires some
  # coding.
  custom-mapper:
    build:
      context: ..
      dockerfile: ./examples/custom-mapper/Dockerfile

  # This is a simple Python application that uses the TkeClient class to
  # register itself and request knowledge that it then prints.
  tree-printer:
    build:
      context: ..
      dockerfile: ./examples/tree-printer/Dockerfile

  # This is a database that is used to demonstrate the dynamic authorization
  # capabilities of the knowledge mapper. Currently, you still have to manually
  # insert the authorization policies into the database.
  auth-db:
    image: mariadb:10.5
    volumes:
      - ./auth-db/seed_data:/docker-entrypoint-initdb.d/:ro
      - auth-db-data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: knowledge_mapper_db
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_RANDOM_ROOT_PASSWORD: 1
  
  # UI for the auth database to be able to easily change it. Add a rule here:
  # http://localhost:8080/?server=auth-db&username=user&db=knowledge_mapper_db&edit=policies
  adminer:
    image: adminer:4.8.1
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: auth-db

  dynamic-auth-mapper:
    build:
      context: ..
      dockerfile: ./examples/dynamic-auth-mapper/Dockerfile
    environment:
      SPARQL_USERNAME: user
      SPARQL_PASSWORD: password

volumes:
  auth-db-data:
