services:
  # This service is the TNO Knowledge Engine runtime where all interoperability is 
  tke-runtime:
    image: ci.tno.nl/tke/knowledge-engine/smart-connector-rest-dist:1.0.2
    ports:
      - 8280:8280
  
  # Data source 1: A SPARQL endpoint.
  fuseki:
    build:
      context: ./fuseki
      args:
        JENA_VERSION: 4.3.2
    command: ["--config=/fuseki/config/config.ttl"]

  # Knowledge mapper for the SPARQL endpoint
  sparql-mapper:
    build:
      context: ..
      dockerfile: ./examples/sparql-mapper/Dockerfile
    environment:
      SPARQL_USERNAME: admin
      SPARQL_PASSWORD: pw
  
  # Data source 2: An SQL database
  mariadb:
    image: mariadb:10.5
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/seed_data:/docker-entrypoint-initdb.d/:ro
    environment:
      MARIADB_DATABASE: treedb
      MARIADB_USER: user
      MARIADB_PASSWORD: pw
      MARIADB_RANDOM_ROOT_PASSWORD: 1

  # Knowledge mapper for the SQL database
  sql-mapper:
    build:
      context: ..
      dockerfile: ./examples/sql-mapper/Dockerfile

  # This is a custom knowledge mapper without an underlying data source that
  # uses a Python function to generate its data. You can imagine that it is
  # possible to disclose sources like REST APIs this way, but it requires some
  # coding.
  custom-mapper:
    build:
      context: ..
      dockerfile: ./examples/custom-mapper/Dockerfile
